### ISSUE TITLE
v100 step3 oom

### ISSUE THREAD

**Issue by iamsile** [l294265421/alpaca-rlhf#6]
您好，我在运行第三步的时候一直报oom这个错误，具体信息如下
File "/opt/conda/envs/mplug_owl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 250.00 MiB (GPU 6; 31.75 GiB total capacity; 30.95 GiB already allocated; 21.75 MiB free; 30.98 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

我使用的是8卡的v100，我将batchsize相关的都调成1了，max_seq_len设小了，lora_dim设成了1，lora_module_name设置成q_proj，请问还有其他办法来优化吗？

**Comment by yanshanjing** [comment]
zero stage 是 3吗？

**Comment by iamsile** [comment]
是的，--actor_zero_stage 3 --critic_zero_stage 3，两个都是3，actor模型和critic模型都是7b的

**Comment by l294265421** [comment]
正常情况下，应该是够的。之前尝试zero stage = 3也有遇到类似问题，看起来像是deepspeed chat会把4个模型都加载进每个卡，而不是在一张卡里加载模型，然后分拆到各个卡，导致显存不足。不确定zero stage = 3还需要额外的设置？

**Comment by iamsile** [comment]
加载过程中就报错了，直接oom了。。。。还没有到训练阶段

**Comment by l294265421** [comment]
至少在目前的配置下，Deepspeed chat的模型加载过程还有些问题，下面是发现的一些问题，先发出来供大家参考，具体怎么解，还在看：
（1）模型是现在加载进来，再分拆到各个卡上，分拆前，有显存峰值。可能的解决方案是像加载critic一样，先加载到内存，而不是显存：
critic_model.load_state_dict(
            torch.load(model_ckpt_path, map_location='cpu'))
（2）加载ref之后，模型并没有分拆到各个卡上
（3）另外看起来，每个llama 7b模型，占了20G+的显存，比预期的13G大很多

1. 加载actor
model = model_class.from_pretrained(
            model_name_or_path,
            from_tf=bool(".ckpt" in model_name_or_path),
            config=model_config,
            torch_dtype=torch.float16
        )
![图片](https://github.com/l294265421/alpaca-rlhf/assets/9948265/6fa46785-d59d-4149-b4d5-69fdfac82b62)

actor_engine, *_ = deepspeed.initialize(model=actor_model,
                                                optimizer=optim,
                                                lr_scheduler=lr_scheduler,
                                                config=ds_config)
![图片](https://github.com/l294265421/alpaca-rlhf/assets/9948265/a43305ec-8f08-45a6-87b9-c14f773ddda6)

2. 加载ref
model = model_class.from_pretrained(
            model_name_or_path,
            from_tf=bool(".ckpt" in model_name_or_path),
            config=model_config,
            torch_dtype=torch.float16
        )
![图片](https://github.com/l294265421/alpaca-rlhf/assets/9948265/a078a0f2-4870-4268-9deb-c938e0074342)

ref_engine, *_ = deepspeed.initialize(model=ref_model,
                                              config=ds_config)
![图片](https://github.com/l294265421/alpaca-rlhf/assets/9948265/4f8d84ce-ade8-4463-9c6f-7b3a798f51b5)

3. 加载critic
critic_engine, *_ = deepspeed.initialize(model=critic_model,
                                                 optimizer=optim,
                                                 lr_scheduler=lr_scheduler,
                                                 config=ds_config)
![图片](https://github.com/l294265421/alpaca-rlhf/assets/9948265/92f373ea-8660-499a-975e-40a102f09d27)



4. 加载reward
reward_engine, *_ = deepspeed.initialize(model=reward_model,
                                                 config=ds_config)
![图片](https://github.com/l294265421/alpaca-rlhf/assets/9948265/007f617b-c25d-4b91-b6ba-f2ba2c66e00d)

**Comment by iamsile** [comment]
感谢大佬的答复，我在想想办法

**Comment by l294265421** [comment]
> 感谢大佬的答复，我在想想办法

试试offload，看DeepSpeed Chat的官方代码，直接去掉下面的声明就行
assert not args.offload, "zero-offload is not currently supported but coming soon!"

相关issue:
https://github.com/microsoft/DeepSpeedExamples/pull/553

**Comment by yanshanjing** [comment]
> @yanshanjing 请教您一个问题，deepspeed.initialize后，模型的权重全部就置为空了吗？

应该不会吧，不然预训练模型没有办法用了。

**Comment by iamsile** [comment]
@l294265421 好的，我去试试，多谢大佬

**Comment by iamsile** [comment]
@yanshanjing 刚刚实验了一下，zero2模式下开启offload，仍然是显存oom

**Comment by iamsile** [comment]
您好，这个问题我后面解决了，用zero3模式训练可以解决oom的问题
